# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.credential_kind import CredentialKind  # noqa: F401,E501
from swagger_server.models.internal_rest_credentials import InternalRestCredentials  # noqa: F401,E501
from swagger_server.models.object_key import ObjectKey  # noqa: F401,E501
from swagger_server import util


class AdapterConfig(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, adapter_key: ObjectKey=None, credential: CredentialKind=None, internal_rest_credential: InternalRestCredentials=None):  # noqa: E501
        """AdapterConfig - a model defined in Swagger

        :param adapter_key: The adapter_key of this AdapterConfig.  # noqa: E501
        :type adapter_key: ObjectKey
        :param credential: The credential of this AdapterConfig.  # noqa: E501
        :type credential: CredentialKind
        :param internal_rest_credential: The internal_rest_credential of this AdapterConfig.  # noqa: E501
        :type internal_rest_credential: InternalRestCredentials
        """
        self.swagger_types = {
            'adapter_key': ObjectKey,
            'credential': CredentialKind,
            'internal_rest_credential': InternalRestCredentials
        }

        self.attribute_map = {
            'adapter_key': 'adapterKey',
            'credential': 'credential',
            'internal_rest_credential': 'internalRestCredential'
        }
        self._adapter_key = adapter_key
        self._credential = credential
        self._internal_rest_credential = internal_rest_credential

    @classmethod
    def from_dict(cls, dikt) -> 'AdapterConfig':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AdapterConfig of this AdapterConfig.  # noqa: E501
        :rtype: AdapterConfig
        """
        return util.deserialize_model(dikt, cls)

    @property
    def adapter_key(self) -> ObjectKey:
        """Gets the adapter_key of this AdapterConfig.


        :return: The adapter_key of this AdapterConfig.
        :rtype: ObjectKey
        """
        return self._adapter_key

    @adapter_key.setter
    def adapter_key(self, adapter_key: ObjectKey):
        """Sets the adapter_key of this AdapterConfig.


        :param adapter_key: The adapter_key of this AdapterConfig.
        :type adapter_key: ObjectKey
        """
        if adapter_key is None:
            raise ValueError("Invalid value for `adapter_key`, must not be `None`")  # noqa: E501

        self._adapter_key = adapter_key

    @property
    def credential(self) -> CredentialKind:
        """Gets the credential of this AdapterConfig.


        :return: The credential of this AdapterConfig.
        :rtype: CredentialKind
        """
        return self._credential

    @credential.setter
    def credential(self, credential: CredentialKind):
        """Sets the credential of this AdapterConfig.


        :param credential: The credential of this AdapterConfig.
        :type credential: CredentialKind
        """

        self._credential = credential

    @property
    def internal_rest_credential(self) -> InternalRestCredentials:
        """Gets the internal_rest_credential of this AdapterConfig.


        :return: The internal_rest_credential of this AdapterConfig.
        :rtype: InternalRestCredentials
        """
        return self._internal_rest_credential

    @internal_rest_credential.setter
    def internal_rest_credential(self, internal_rest_credential: InternalRestCredentials):
        """Sets the internal_rest_credential of this AdapterConfig.


        :param internal_rest_credential: The internal_rest_credential of this AdapterConfig.
        :type internal_rest_credential: InternalRestCredentials
        """

        self._internal_rest_credential = internal_rest_credential
