# coding: utf-8

"""
    Adapter API

    The API contract is defined using a standard OpenAPI specification to simplify adapter development.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

#  Copyright 2022 VMware, Inc.
#  SPDX-License-Identifier: Apache-2.0

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.adapter_config import AdapterConfig  # noqa: E501
from swagger_client.rest import ApiException


class TestAdapterConfig(unittest.TestCase):
    """AdapterConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAdapterConfig(self):
        """Test AdapterConfig"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.adapter_config.AdapterConfig()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
