# coding: utf-8

"""
    Adapter API

    The API contract is defined using a standard OpenAPI specification to simplify adapter development.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.certificate_config import CertificateConfig  # noqa: E501
from swagger_client.rest import ApiException


class TestCertificateConfig(unittest.TestCase):
    """CertificateConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCertificateConfig(self):
        """Test CertificateConfig"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.certificate_config.CertificateConfig()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
