# coding: utf-8
#  Copyright 2023 VMware, Inc.
#  SPDX-License-Identifier: Apache-2.0
from __future__ import absolute_import

from datetime import date
from datetime import datetime
from typing import Dict
from typing import List

from swagger_server import util
from swagger_server.models.base_model_ import Model


class CollectionWindow(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, start_time: float = None, end_time: float = None):  # noqa: E501
        """CollectionWindow - a model defined in Swagger

        :param start_time: The start_time of this CollectionWindow.  # noqa: E501
        :type start_time: float
        :param end_time: The end_time of this CollectionWindow.  # noqa: E501
        :type end_time: float
        """
        self.swagger_types = {"start_time": float, "end_time": float}

        self.attribute_map = {"start_time": "startTime", "end_time": "endTime"}
        self._start_time = start_time
        self._end_time = end_time

    @classmethod
    def from_dict(cls, dikt) -> "CollectionWindow":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CollectionWindow of this CollectionWindow.  # noqa: E501
        :rtype: CollectionWindow
        """
        return util.deserialize_model(dikt, cls)

    @property
    def start_time(self) -> float:
        """Gets the start_time of this CollectionWindow.


        :return: The start_time of this CollectionWindow.
        :rtype: float
        """
        return self._start_time

    @start_time.setter
    def start_time(self, start_time: float):
        """Sets the start_time of this CollectionWindow.


        :param start_time: The start_time of this CollectionWindow.
        :type start_time: float
        """

        self._start_time = start_time

    @property
    def end_time(self) -> float:
        """Gets the end_time of this CollectionWindow.


        :return: The end_time of this CollectionWindow.
        :rtype: float
        """
        return self._end_time

    @end_time.setter
    def end_time(self, end_time: float):
        """Sets the end_time of this CollectionWindow.


        :param end_time: The end_time of this CollectionWindow.
        :type end_time: float
        """

        self._end_time = end_time
